### ISSUE TITLE
Implement Multiply Function

### ISSUE THREAD

**Issue by DanielSauve** [DanielSauve/functional-rs#1]
There is a method called `multiply` that lives in `src/multiply.rs`. It needs to be fixed. It expects 2 arguments, both of which are numerics of the same type. It should return the numbers multiplied together.

# Acceptance Criteria:
1. The function has been implemented
2. `mod multiply` has been added to `src/lib.rs`
3. Running cargo test results in all tests passing
4. You have added tests for a new method and a skeleton for that method for someone else to work on
5. (Optional) Write more tests to ensure your method is bullet proof

Comment below if you would like to take on this task!

**Comment by tyjoll96** [comment]
I would like to take on this task. 🤷‍♂️

**Comment by DanielSauve** [comment]
Done!
